# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/papers-core/src/db/schema.rs"

[migrations_directory]
dir = "crates/papers-core/migrations"
